### PR TITLE
Remove plannedCapcity after a timeout

### LINKED ISSUE #172: Spot instances are not provisioning if target capacity decreases to 0
I'have noticed the strange behavior of plugin. "Minimum cluster size" in Jenkins configured equals to 0. 
When "Target Capacity" is 0 and builds start Spot fleet plugin doesn't provision new instances and builds can stay in queue for hours and there are no errors in AWS Console or Jenkins logs.
If go to AWS Console and manually change "Target Capacity" from 0 to 1 spot instances are provisioning good.
I not sure if the issue related to scaling down to 0 but in another Jenkins where "Minimum cluster size" configured equals 1 this issue is absent.
Please advice.

**To reproduce:**
Create new spot request maually for use in Jenkins and set "Target Capacity" to 0
Add fleet to Jenkins via this plugin, scaling from 0-4
Start build on spot instance in Jenkins

**Expected behavior:**
New spot instances are provisioned automatically by plugin

**Actual behavior:**
Builds stay in queue for hours until you manually change "Target capacity" to 1 in AWS console.

**Versions**
Jenkins 2.204.2
EC2 Fleet Jenkins Plugin 1.3.1

### PR DESCRIPTION
**Pull request by haugenj**
Fixes #172 

In 172 we don't scale up from 0 because plannedNodes persist in Jenkins's plannedCapacitySnapshot. This happens when the fleet configuration changes in between Jenkins calling provision() on a fleet and the fleet's next update cycle where it actually tries to scale up. 

This change uses ScheduledFutures to cancel plannedCapacitySnapshot futures after a timeout of 3 cloud update cycles unless explicitly canceled. This means that if the fleet is modified, or if a fleet is completely removed, we're still covered.

### CODE REVIEW

File: src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java [hunk 1]
```diff
@@ -240,6 +246,11 @@ public int getInitOnlineTimeoutSec() {
         return initOnlineTimeoutSec == null ? DEFAULT_INIT_ONLINE_TIMEOUT_SEC : initOnlineTimeoutSec;
     }
 
+    public int getScheduledFutureTimeoutSec() {
+        // Wait 3 update cycles before timing out. Gives a little cushion in case fleet is under modification
+        return getCloudStatusIntervalSec() * 3;
```
Comment (imuqtadir) [inline src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: Cloud Status Interval could be as little as 1-3 seconds. Do you think we should be depending on cloudnanny interval or have sort of constant value of 60-90 seconds?

Comment (haugenj) [reply src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: I think it should be based on the Cloud Status Interval because we will only cancel timeout when update() is run, which depends on Cloud Status Interval. And if the interval is small then we might still get value from timing out early if another fleet could handle that job. 

I'm not against adding a default longer minimum though for cases when Cloud Status Interval is small. Maybe something like
```
private final int MIN_SCHEDULED_FUTURE_TIMEOUT = 30;

public int getScheduledFutureTimeoutSec() {
  final int timeout = getCloudStatusIntervalSec() * 3;
  return timeout > MIN_SCHEDULED_FUTURE_TIMEOUT ? timeout : MIN_SCHEDULED_FUTURE_TIMEOUT;
}
```

Thoughts?

Comment (imuqtadir) [reply src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: I was thinking about a scenario when a customer has launched way too many instances in their previous update and `fleet under modification` will last longer than ``cloud interval * 3`` (where cloud interval is small).  AFAIK, fleet will remain in modifying state until the target capacity is achieved. So having something like `MIN_SCHEDULED_FUTURE_TIMEOUT` might be helpful.

Comment (haugenj) [reply src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: For that case, if we scale up in the previous update the new scheduled futures will be cancelled and the Jenkins futures will be left alone. 

So it'd look like
1. Add jobs to queue
2. Jenkins finds jobs and calls provision on fleet
3. Scheduled futures start
4. Update happens, we start to scale up
5. Scheduled futures are cancelled
6. Next update is called, fleet is still scaling so it's in modification state now

Comment (imuqtadir) [reply src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: I meant the scenario where:

1. Add jobs to queue
2. Jenkins updates fleet target to a relatively large number
3. Add more jobs to queue
4. Target will not be updated as fleet is still in modifying state launching large number of instances
5. The second round of futures might timeout if Cloud status interval is small

Comment (haugenj) [reply src/main/java/com/amazon/jenkins/ec2fleet/EC2FleetCloud.java:251]: I think that's actually ok though, because if those futures are cancelled then another fleet might be able to provision capacity for those jobs

**Review by imuqtadir — APPROVED** [review]
lgtm
